"""
Schemas package - contains Pydantic models for API requests/responses.
"""
from app.schemas.token import (
    Token,
    TokenPayload,
    RefreshTokenRequest,
    LoginRequest,
    LoginResponse,
    RegisterRequest,
    RegisterResponse,
    PasswordResetRequest,
    PasswordResetConfirm,
    ChangePasswordRequest,
    Message,
    HealthCheck,
    UserBase,
    UserCreate,
    UserUpdate,
    UserResponse,
    UserInDB,
    UserListResponse,
)

from app.schemas.user import (
    UserBase,
    UserCreate,
    UserUpdate,
    UserResponse,
    UserInDB,
)

from app.schemas.role import (
    RoleBase,
    RoleCreate,
    RoleUpdate,
    RoleInDB,
    RoleResponse,
    RoleListResponse,
    RoleDetailResponse,
    RoleCreateInput,
    RoleUpdateInput,
    RoleBlueprintGenerateInput,
    CompetencyResponse,
    InterviewStageResponse,
    RoleBlueprintResponse,
    AIGeneratedBlueprint,
    GenerateBlueprintRequest,
    GenerateBlueprintResponse,
    SeniorityLevel,
    InterviewType,
)

from app.schemas.workflow import (
    WorkflowBase,
    WorkflowCreate,
    WorkflowUpdate,
    WorkflowResponse,
    WorkflowListResponse,
    WorkflowDetailResponse,
    WorkflowStage,
    WorkflowStageCreate,
    WorkflowStageUpdate,
    MoveCandidateRequest,
    BulkMoveCandidateRequest,
    StageTransitionResult,
    BulkStageTransitionResult,
    InterviewerAssignmentRequest,
    InterviewerReassignmentRequest,
    CancelAssignmentRequest,
    AssignmentResponse,
    StageAssignmentsResponse,
    FeedbackStatusResponse,
    PendingFeedbackResponse,
    FeedbackCompletionStats,
    CanMoveCandidateResponse,
    WorkflowStatsResponse,
    DefaultWorkflowTemplate,
    WorkflowTemplateResponse,
)

__all__ = [
    # Token schemas
    "Token",
    "TokenPayload",
    "RefreshTokenRequest",
    "LoginRequest",
    "LoginResponse",
    "RegisterRequest",
    "RegisterResponse",
    "PasswordResetRequest",
    "PasswordResetConfirm",
    "ChangePasswordRequest",
    "Message",
    "HealthCheck",
    # User schemas
    "UserBase",
    "UserCreate",
    "UserUpdate",
    "UserResponse",
    "UserInDB",
    "UserListResponse",
    # Role schemas
    "RoleBase",
    "RoleCreate",
    "RoleUpdate",
    "RoleInDB",
    "RoleResponse",
    "RoleListResponse",
    "RoleDetailResponse",
    "RoleCreateInput",
    "RoleUpdateInput",
    "RoleBlueprintGenerateInput",
    "CompetencyResponse",
    "InterviewStageResponse",
    "RoleBlueprintResponse",
    "AIGeneratedBlueprint",
    "GenerateBlueprintRequest",
    "GenerateBlueprintResponse",
    "SeniorityLevel",
    "InterviewType",
    # Workflow schemas
    "WorkflowBase",
    "WorkflowCreate",
    "WorkflowUpdate",
    "WorkflowResponse",
    "WorkflowListResponse",
    "WorkflowDetailResponse",
    "WorkflowStage",
    "WorkflowStageCreate",
    "WorkflowStageUpdate",
    "MoveCandidateRequest",
    "BulkMoveCandidateRequest",
    "StageTransitionResult",
    "BulkStageTransitionResult",
    "InterviewerAssignmentRequest",
    "InterviewerReassignmentRequest",
    "CancelAssignmentRequest",
    "AssignmentResponse",
    "StageAssignmentsResponse",
    "FeedbackStatusResponse",
    "PendingFeedbackResponse",
    "FeedbackCompletionStats",
    "CanMoveCandidateResponse",
    "WorkflowStatsResponse",
    "DefaultWorkflowTemplate",
    "WorkflowTemplateResponse",
]

